[language-server]
nil = { command = "nil" }
taplo = { command = "taplo", args = ["lsp", "stdio"] }
yaml-language-server = { command = "yaml-language-server", args = ["--stdio"] }
marksman = { command = "marksman", args = ["server"] }
nu-lsp = { command = "nu", args = ["--lsp"] }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server.config]
provideFormatter = true
format = { enable = true }
json = { validate = { enable = true } }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt", args = ["--filename", "%{buffer_name}"] }
language-servers = ["nil"]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }
language-servers = ["bash-language-server"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["yaml-language-server"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }
language-servers = ["vscode-json-language-server"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
language-servers = ["marksman"]

[[language]]
name = "nu"
language-servers = ["nu-lsp"]
